fitmodel <- function(x, model, count, nRand = 999, ...){
  if(!(model %in%  c("dominanceDecay", "dominancePreemp", "MacArthurFraction", 
                     "powerFraction", "randAssort", "randFraction"))){
    stop(paste("\n'model' must be one of this:", '"dominanceDecay", "dominancePreemp", "MacArthurFraction", "powerFraction", "randAssort", "randFraction"'))
  }
  
  if(!is.matrix(x) & !is.data.frame(x)){
    stop("\n'x' must be a data frame or a matrix")
  }
  
  if(length(x[ ,1]) < 2){
    stop("\nYou must have more than one replicates in lines")
  }
  
  if(is.null(count)){
    stop("\n'count' must be specified")
  }
  
  # Number of replicates and total species.
  n <- dim(x)[1]
  S <- dim(x)[2]
  # Total abundance of each replicates.
  N <- apply(x, MARGIN = 1, FUN = sum)
  
  # 'nRand' means and variances of 'n' simulations to the model.
  M <- matrix(nrow = nRand, ncol = S)
  V <- matrix(nrow = nRand, ncol = S)
  for(i in 1:nRand){
    sim <- matrix(nrow = n, ncol = S)
    for(j in 1:n){
      sim[j, ] <- do.call(model, list(N = N[j], S = S, count = count, ... = ...))
      # Transform to relative abundance
      sim[j, ] <- sim[j, ] / sum(sim[j, ])
    }
    M[i, ] <- apply(sim, MARGIN = 2, FUN = mean)
    V[i, ] <- apply(sim, MARGIN = 2, FUN = var)
  }
  
  # Transform each replicate to relative abundance.
  for(i in 1:n){
    x[i, ] <- sort(x[i, ] / sum(x[i, ]), decreasing = TRUE)
  }
  
  # Observed relative abundance mean and variance of replicates.
  M0 <- apply(x, MARGIN = 2, FUN = mean)
  V0 <- apply(x, MARGIN = 2, FUN = var)
  
  # Probability that the observed mean and variance are predicted by the model.
  pM0 <- c()
  pV0 <- c()
  for(i in 1:S){
    # p = (b+1)/(m+1)
    pM0[i] <- 2 * min((sum(M[ ,i] < M0[i]) + 1) / (nRand + 1),
                      (sum(M[ ,i] > M0[i]) + 1) / (nRand + 1))
    pV0[i] <- 2 * min((sum(V[ ,i] < V0[i]) + 1) / (nRand + 1),
                      (sum(V[ ,i] > V0[i]) + 1) / (nRand + 1))
  }
  
  # Global statistic (T observed) to combined p of all ranks.
  TM0 <- -2 * sum(log(pM0))
  TV0 <- -2 * sum(log(pV0))
  
  # Distribution of T values.
  dTM <- c()
  dTV <- c()
  for(i in 1:nRand){
    pM <- c()
    pV <- c()
    for(j in 1:S){
      # p = (b+1)/(m+1)
      pM[j] <- 2 * min(((sum(c(M[-i,j], M0[j]) < M[i,j]) + 1) / (nRand + 1)), 
                       ((sum(c(M[-i,j], M0[j]) > M[i,j]) + 1) / (nRand + 1)))
      pV[j] <- 2 * min(((sum(c(V[-i,j], V0[j]) < V[i,j]) + 1) / (nRand + 1)), 
                       ((sum(c(V[-i,j], V0[j]) > V[i,j]) + 1) / (nRand + 1)))
    }
    dTM[i] <- -2 * sum(log(pM))
    dTV[i] <- -2 * sum(log(pV))
  }
  
  # Probability that T observed is drawn from T values generated by the model.
  pvalueM <- sum(dTM > TM0) / (nRand + 1)
  pvalueV <- sum(dTV > TV0) / (nRand + 1)
  
  return(list(dTmean = dTM, dTvar = dTV, TMobs = TM0, TVobs = TV0,
              simulations = matrix(c(apply(M, 2, mean), apply(V, 2, mean)), nrow = 2, ncol = S, byrow = TRUE,
                                   dimnames = list(c("mean", "variance"), paste("rank", 1:S, sep = ""))),
              stat = matrix(c(pvalueM, pvalueV), nrow = 2, ncol = 1, 
                          dimnames = list(c("mean", "variance"), "p-value"))))
}
